---

- name: Install docker and git
  gather_facts: No
  hosts: server_all

  roles:
    - update-centos
    - install-docker
    - install-git
    - install-pip-docker

- name: Create  db docker containers on localhost and push to gcp registry
  gather_facts: No
  hosts: localhost

  roles:
  #  - docker-carts-db
    - docker-catalogue-db

- name: Run db docker containers on db-server
  gather_facts: No
  hosts: db

  roles:
    - docker-carts-db-run
    - docker-catalogue-db-run
  #  - docker-user-db

- name: Create docker containers network on app-server
  gather_facts: No
  hosts: app
  
  roles:
    - add-docker-network-and-volumes
