---
# tasks file for catalogue-run
- name: Docker Login
  docker_login:
    registry: https://gcr.io
    username: _json_key
    debug: true
    password: " {{ lookup('file', '/var/lib/jenkins/credential/if-101-demo1-02c2a2eae285.json')}}"
  become: yes
  

- name: Run catalogue-db container
  docker_container:
    name: catalogue-db
    image: "gcr.io/if-101-demo1/catalogue-db:latest"
    ports:
      - "3306:3306"
    restart_policy: always
    pull: yes
    user: root
  become: yes