filebeat:
  # List of prospectors to fetch data.
  inputs:
    -
      paths:
      #  - /usr/share/filebeat
        - /var/log/messages
      #  - /var/log/*.log
      encoding: plain
      input_type: log
      #document_type: syslog
      #registry: /var/lib/filebeat/registry
      #tail_files: true
      tags: ["system-log"]

    - 
      type: docker
      combine_partial: true
      encoding: "plain"
      # json.keys_under_root: true
      # json.add_error_key: true
      # json.message_key: log
      #multiline.pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.pattern: "^[[:space:]]+(at|\\.{3})\\b|^Caused by:"
      multiline.negate: false
      #multiline.negate: true
      multiline.match: after
      containers:
        path: "/var/lib/docker/containers"
        stream: "all"
        ids:
          - "*"

processors:
  - add_docker_metadata: ~

console:
  #Pretty print json event
  pretty: true

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elk-server:9200}'
  username: 'elastic'
  password: 'changeme'

setup.kibana:
host: "elk-server:5601"
username: "elastic"
password: "changeme"