filebeat:
  # List of prospectors to fetch data.
  prospectors:
    # Magento log prospector
    -
      paths:
        - /var/log/messages
        - /var/log/*.log
      encoding: plain
      input_type: log
      #document_type: syslog
      #registry: /var/lib/filebeat/registry
      #tail_files: true
      tags: ["system-log"]

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elk:9200}'
  username: 'elastic'
  password: 'changeme'
