filebeat:
  
  inputs:
    -
      paths:
        - /var/log/messages
      
      encoding: plain
      input_type: log
      tags: ["system-log"]

    - 
      type: docker
      combine_partial: true
      encoding: "plain"
      #multiline.pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.pattern: "^[[:space:]]+(at|\\.{3})\\b|^Caused by:"
      multiline.negate: false
      #multiline.negate: true
      multiline.match: after
      containers:
        path: "/var/lib/docker/containers"
        stream: "all"
        ids:
          - "*"
      tags: ["docker-log"]

processors:
  - add_docker_metadata: ~

console:
  #Pretty print json event
  pretty: true

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elk-server:9200}'
  username: 'elastic'
  password: 'changeme'

setup.kibana:
host: "elk-server:5601"
username: "elastic"
password: "changeme"