filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- type: docker
  combine_partial: true
  encoding: "utf-8"
  # json.keys_under_root: true
  # json.add_error_key: true
  # json.message_key: log
  #multiline.pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.pattern: "^[[:space:]]+(at|\\.{3})\\b|^Caused by:"
  multiline.negate: false
  #multiline.negate: true
  multiline.match: after
  containers:
    path: "/var/lib/docker/containers"
    stream: "all"
    ids:
      - "*"
# filebeat.autodiscover:
#   providers:
#     - type: docker
#       multiline.pattern: "^[[:space:]]+(at|\\.{3})\\b|^Caused by:"
#       multiline.negate: false
#       multiline.match: after
#       hints.enabled: true

processors:
- add_docker_metadata: ~
    #host: "unix:///var/run/docker.sock"

# - decode_json_fields:
#      fields: ["field1", "field2", ...]
#      process_array: false
#      max_depth: 1
#      target: "json"
#      overwrite_keys: false
#      add_error_key: true

# - decode_json_fields:
#     fields: ["message"]
#     target: "json"
#     overwrite_keys: true

# processors:
# - add_cloud_metadata: ~

# - decode_json_fields:
#     fields: ["message"]
#     target: "json"
#     overwrite_keys: true

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elk:9200}'
  username: 'elastic'
  password: 'changeme'

logging.json: true
logging.metrics.enabled: false



  



# output.elasticsearch:
#   hosts: ["elasticsearch:9200"]
#   username: 'elastic'
#   password: 'changeme'
#   indices:
#     - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

