filebeat:
  # List of prospectors to fetch data.
  prospectors:
    # Magento log prospector
    -
      paths:
        - /var/log/messages
      encoding: plain
      input_type: log
      
output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elk:9200}'
  username: 'elastic'
  password: 'changeme'
