---
# tasks file for run-docker-elk

  - name: Create kibana container
    docker_container:
      name: kibana
      image: kibana:7.4.2
      network_mode: "socks"
      ports:
        - "5601:5601"
      recreate: yes
      state: started 

  - name: copy elasticksearch conf 
    copy:
      src: "{{ WORKSPACE }}/elasticsearch.yml"
      dest: /tmp
      mode: 0644
      owner: 1000
      group: 1000
      force: yes
    become: yes

  - name: Create ElasticSearch container
    docker_container:
      name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
      network_mode: "socks"
      ports:
        - "9200:9200"
        - "9300:9300"
      env: 
        ES_JAVA_OPTS: "-Xms750m -Xmx750m"
        bootstrap.memory_lock: "true"
       # es.enforce.bootstrap.checks: "true"
      ulimits:
        - "nofile:262144:262144"
        - "nproc:65535:65535"
        - "memlock:-1:-1"
      volumes:
        - /tmp/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:Z
      #user:   elasticsearch
      recreate: yes
      state: started         

  