---
# tasks file for catalogue-run
- name: Docker Login
  docker_login:
    registry: https://gcr.io
    username: _json_key
    debug: true
    password: " {{ lookup('file', '/var/lib/jenkins/credential/if-101-demo1-02c2a2eae285.json')}}"
  become: yes
  
- name: Run catalogue container
  docker_container:
    name: catalogue
    image: "gcr.io/if-101-demo1/catalogue:latest"
    ports:
      - "8080:80"
    restart_policy: always
    networks:
      - name: socks
    etc_hosts:
        catalogue-db: "{{ db_host }}"
    pull: yes
    recreate: yes
    state: present 
    user: root
  become: yes