---
# tasks file for catalogue-build

- name: Clone catalogue
  git:
    repo: 'https://github.com/ryzhan/catalogue.git'
    dest: "{{ WORKSPACE }}/microservices/catalogue"

- name: Docker Login
  docker_login:
    registry: https://gcr.io
    username: _json_key
    debug: true
    password: " {{ lookup('file', '/var/lib/jenkins/credential/if-101-demo1-02c2a2eae285.json')}}"

- name: build catalogue
  docker_image:
    name: gcr.io/if-101-demo1/catalogue:3.0.0-{{ BUILD_NUMBER }}
    build:
      path: "{{ WORKSPACE }}/microservices/catalogue"
      dockerfile: "{{ WORKSPACE }}/microservices/catalogue/docker/catalogue/Dockerfile"
      pull: yes
    debug: yes
    source: build
    push: yes

- name: TAG front-end
  docker_image:
    name: gcr.io/if-101-demo1/catalogue:3.0.0-{{ BUILD_NUMBER }}
    repository: gcr.io/if-101-demo1/catalogue:latest
    force_tag: yes
    source: local
    push: yes

- name: Remove image latest
  docker_image:
    state: absent
    force_absent: yes
    name: gcr.io/if-101-demo1/catalogue
    tag: "{{ item }}"
  with_items:
    - "3.0.0-{{ BUILD_NUMBER }}"
    - "latest"
     
# - name: Remove image latest
#   docker_image:
#     state: absent
#     name: gcr.io/if-101-demo1/catalogue
#     tag: latest

# - name: Remove image version
#   docker_image:
#     state: absent
#     name: gcr.io/if-101-demo1/catalogue
#     tag: "0.0.3-{{ BUILD_NUMBER }}"