---
- name: Build docker image and push to google registry
  gather_facts: No
  hosts: localhost

  roles:
    - front-end-build
  
- name: run docker container in app-server
  gather_facts: No
  hosts: app

  roles:
    - front-end-run
  