---

- name: Install docker and git
  gather_facts: No
  hosts: server_all

  roles:
    - update-centos
    - install-docker
    #- install-git
    - install-pip-docker
    - add-docker-network-and-volumes

- name: Create  db docker containers on localhost and push to gcp registry
  gather_facts: No
  hosts: localhost

  roles:
  #  - docker-carts-db
    - docker-catalogue-db

- name: Run db docker containers on db-server
  gather_facts: No
  hosts: db

  roles:
    - docker-carts-db-run
    - docker-catalogue-db-run
    - run-docker-filebeat

- name: Run docker containers on app-server
  gather_facts: No
  hosts: app

  roles:
    - run-docker-filebeat
  
# - name: Run elk docker containers on elk-server
#   gather_facts: No
#   hosts: elk

#   roles:
#     - run-docker-elk



